# Utilisation d'une image PostgreSQL comme base
FROM postgres:latest

# Définition des variables d'environnement pour le mot de passe de l'utilisateur et le nom de la base de données
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=123
ENV POSTGRES_DB=exercice_docker
